import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const dm_sans = localFont({
  src: [
    {
      path: '../font/DMSans-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../font/DMSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../font/DMSans-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../font/DMSans-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-dm',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "NorthStar Growth Advisors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}